language: julia

os:
  - osx
  - linux

julia:
  - 1.3

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.3
      os: osx
      script:
        - julia --project=docs/ --color=yes -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        # - julia --project=docs/ --color=yes -e 'ENV["PYTHON"]="~/.julia/conda/3/bin"; using Pkg; Pkg.add("PyCall"); Pkg.build("PyCall"); ENV'
        - julia --project=docs/ --color=yes docs/make.jl
      after_success: skip

notifications:
  email: false
