language: julia

os:
  - osx
  - linux

julia:
  - 1.3
  - 1.4
  - nightly

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.3
      os: osx
      script:
        - pwd && echo '******' && cd ~ && ls -la && echo '******' && cd .julia && ls && echo '******' && cd conda && ls && echo '******' && pwd
        - julia --project=docs/ --color=yes -e 'ENV["PYTHON"]="~/.julia/conda/3/bin"; using Pkg; Pkg.build("PyCall"); ENV'
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip


# notifications:
#   email: true
