name = "LAP_julia"
uuid = "f6db0fed-51e0-47ff-b019-331ad395592a"
authors = ["David Kunz <epicfail.davidkunz@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
