name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.3
      - name: Install dependencies
        run: julia --project=docs/ --color=yes -e 'ENV["DOCUMENTER_DEBUG"] = "true"; using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: find julia conda python
        run: cd ~ && pwd && echo '******' && ls -la && cd.julia/conda/3/ && echo '******' && pwd && ls -la && echo '*********' && pwd && cd bin
      - name: Set default python
        run: julia --project=docs/ --color=yes -e 'ENV["PYTHON"]="~/.julia/conda/3/bin"; using Pkg; Pkg.build("PyCall"); ENV'
      - name: Build and deploy
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --color=yes --project=docs/ docs/make.jl  # maybe add 'ENV["DOCUMENTER_DEBUG"] = "true"
